### ISSUE TITLE
Persisting user after page refresh

### ISSUE THREAD

**Issue by dxinteractive** [asyarb/react-use-googlelogin#2]
Hi, this is a great little hook you have here. Docs explain everything well enough to use with no issues. My question is around persisting the current user after page refresh. I read how this is intentionally omitted which is fine, but I'm a bit unclear on how to rehydrate the hook with the knowledge of the current user.

So it looks like `gapi` uses `window.localStorage` by default to persist the current user's auth info - their access token and stuff. Their troubleshooting page [mentions how localStorage is required](https://developers.google.com/people/quickstart/js#troubleshooting) at least. And when I use the `useGoogleLogin()` hook, sign in, refresh the page, and wait for `useGoogleLogin()` to load up `gapi` again, I can see that `gapi` is already persisting the user because I'm able to call `window.gapi.auth2.getAuthInstance().currentUser.get()` and see that it remembers me. The issue I find is that after refreshing and loading `gapi` again, the `useGoogleLogin()` hook doesn't appear to sync its internal state up with the auth state held in `gapi`, so it never re-learns that there is a current authenticated user still hanging about.

Considering that the current user auth is being persisted in local storage by `gapi` whether we like it or not, would you consider making the hook roll with it and sync it's state up with `gapi` after refresh? Or if you don't want to do that, how might I get `useGoogleLogin()` to acknowledge the user that's still signed in and update its state accordingly?

**Comment by asyarb** [comment]
Thanks for trying out the hook! My apologies for the delayed response.

I hadn't realized that `gapi` is already syncing information to `localStorage`. With that being the case, I agree that it makes sense to sync the hook's state on page refresh by checking the value `gapi` is already putting there.

I should have time later this weekend to work on this, so stay tuned for an update!

**Comment by dxinteractive** [comment]
@asyarb ah awesome! Yeah cool, let me know when you have it. I'm happy to help test it out.

I've had success in the past listening to state sign in changes like this:

```js
// on load...
updateSigninStatus(gapi.auth2.getAuthInstance().isSignedIn.get());
// and also listen to state changes after load...
gapi.auth2.getAuthInstance().isSignedIn.listen(updateSigninStatus);

// where updateSigninStatus = (isSignedIn: boolean) => void
```

Means you can set your app / library as a complete slave to the state of `gapi.auth2`, so it responds to stuff like global logouts, or if more than one thing in the same app is interacting with `gapi.auth2`

**Comment by asyarb** [comment]
@dxinteractive I was able to publish version `0.10.0` this weekend which should now support user persistence as well as listening for global logouts. If you run into any issues, please let me know!

The hook also returns an `isInitialized` boolean to signal when `window.gapi` and the returned `googleUser` object should be fully available and persisted. May come in handy during SSR or preventing any janky rapid state changes on page refresh.  There's a new section in the readme that provides additional details on this.

**Comment by dxinteractive** [comment]
@asyarb nice work, I'll try this out tonight. Thanks for this!

**Comment by asyarb** [comment]
Closing this for now since issue seems to be resolved.

**Comment by dxinteractive** [comment]
Hey, finally got around to trying this, works great. Thanks again.
