### ISSUE TITLE
all isLoggedIn in documentation should be isSignedIn

### ISSUE THREAD

**Issue by oldwolf** [asyarb/react-use-googlelogin#5]
Thank you for this library.

found a small mistake, all isLoggedIn in documentation should be isSignedIn instead

cheers

**Comment by asyarb** [comment]
You're totally right. This was renamed a few commits ago and I forgot to update the README to reflect that. I'll get around to updating this when I can.

Thanks for pointing this out! I'll keep this open until I get around to updating it as a reminder.

**Comment by paulwoelfelcpl** [comment]
I've stumbled across the same issue and created a MR #6  for the readme.

**Comment by asyarb** [comment]
@paulwoelfelcpl Thanks for the PR! The updated readme looks good to me. I'll merge these changes in shortly.
